- hosts: localhost
  tasks:
        - name: Install apache
          ansible.builtin.package:
           name: apache
           state: present

- name: "web Server start"
  service:
       name: "httpd"
       state: started
       enabled: yes