- name: install package
  hosts: all
  tasks:
    - name: Install httpd
      ansible.builtin.package:
           become: yes 
           name: httpd
           state: present

    - name: "web Server start"
      service:
       name: "httpd"
       state: started
       enabled: yes

